name: WaybackURLs and Nuclei Scanner

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      targetname: 'cybersigmacs.com'  # Set your default target name here

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install Required Tools
      run: |
        go get github.com/tomnomnom/waybackurls

        # Install Nuclei
        NUCLEI_VERSION="2.9.8"  # Specify the desired version
        wget https://github.com/projectdiscovery/nuclei/releases/download/v${NUCLEI_VERSION}/nuclei_${NUCLEI_VERSION}_linux_amd64.tar.gz
        tar -zxvf nuclei_${NUCLEI_VERSION}_linux_amd64.tar.gz
        sudo mv nuclei /usr/local/bin/

    - name: Run WaybackURLs and Nuclei
      run: |
        outputfile="waybackurls_output.txt"
        nucleioutput="${env.targetname}_nucleioutput.txt"

        echo "[*] Running waybackurls on $env.targetname"
        waybackurls $env.targetname > $outputfile
        echo "[+] waybackurls output saved to $outputfile"

        echo "[*] Running nuclei on $outputfile"
        nuclei -l $outputfile --silent -es info -o $nucleioutput | tee -a log_output.txt
        echo "[+] Nuclei output saved to $nucleioutput"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: scan-results
        path: |
          ${{ github.workspace }}/$outputfile
          ${{ github.workspace }}/$nucleioutput
          ${{ github.workspace }}/log_output.txt
